name = "foo"
main = "src/routes/index.ts"
compatibility_date = "2024-01-29"
workers_dev = false

routes = [{ pattern = "foobar.rustymagnet.xyz", custom_domain = true }]

# serves static folder
assets = { directory = "./public/static", binding = "ASSETS" }

[dev]
port = 8787
local_protocol = "http"

[observability]
enabled = true