name = "foo"
main = "src/routes/index.ts"
compatibility_date = "2024-08-15"
compatibility_flags = ["nodejs_compat"]

workers_dev = false

routes = [{ pattern = "foobar.rustymagnet.xyz", custom_domain = true }]

# serves static folder
assets = { directory = "./public/static", binding = "ASSETS" }

#get overridden by values in the .devs.vars
[vars]
SECURITY_HEADER_NAME = "X-Header"
SECRET_KEY = "dummy"
ENVIRONMENT = "DEVELOPMENT"

[dev]
port = 8787
local_protocol = "http"

[observability]
enabled = true