name = "foo"
main = "src/routes/index.js"
compatibility_date = "2024-01-29"
workers_dev = false

routes = [{ pattern = "foobar.rustymagnet.xyz", custom_domain = true }]

[site]
bucket = "./assets"

rules = [
    { type = "Text", globs = ["**/*.html"], fallthrough = true }
]

[dev]
port = 8787
local_protocol = "http"
