version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build-and-test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: node --version
      - run: npm test
      - run: echo "hello" > test.txt
      - persist_to_workspace:
           root: ~/project
           paths:
             - .

  lint:
    executor: node/default
    steps:
      - attach_workspace:
          at: ~/project
      - run: npx eslint --version
      - run: npm run lint


  check-wrangler-ok:
    executor: node/default
    steps:
      - attach_workspace:
          at: ~/project
      - run: cat test.txt
      - run: npx wrangler --version

  deploy-to-cloudflare:
    executor: node/default
    steps:
      - attach_workspace:
          at: ~/project
      - run: npx wrangler whoami
      - run: npx wrangler deploy

workflows:
  test_and_lint:
    jobs:
      - build-and-test
      - lint:
          requires:
            - build-and-test
      - check-wrangler-ok:
          requires:
            - build-and-test
      - deploy-to-cloudflare:
          requires:
            - check-wrangler-ok
