version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build-and-test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: node --version
      - run: npm test

  check-wrangler-ok:
    executor: node/default
    steps:
      - run: npx wrangler version


workflows:
  test_and_lint:
    jobs:
      - build-and-test
      - check-wrangler-ok:
          requires:
            - build-and-test

