version: 2.1

orbs:
  node: circleci/node@5.0.2

  filter_deployable: &filter_deployable
    filters:
      branches:
        only:
          - master
jobs:
  build-and-test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm     # vitest will fail to find index.js if npm not installed
      - run: npx vitest --version
      - run: npx vitest --run
      - run: echo "hello" > test.txt
      - persist_to_workspace:
           root: ~/project
           paths:
             - .

  lint:
    executor: node/default
    steps:
      - attach_workspace:
          at: ~/project
      - run: npx eslint --version
      - run: npm run lint


  check-wrangler-ok:
    executor: node/default
    steps:
      - attach_workspace:
          at: ~/project
      - run: cat test.txt
      - run: npx wrangler --version
      - run: npx wrangler whoami

  deploy-to-cloudflare:
    executor: node/default
    steps:
      - attach_workspace:
          at: ~/project
      - run: npx wrangler deploy

workflows:
  test_and_lint:
    jobs:
      - build-and-test
      - lint:
          requires:
            - build-and-test
      - check-wrangler-ok:
          requires:
            - build-and-test
      - deploy-to-cloudflare:
          requires:
            - check-wrangler-ok
          <<: *filter_deployable